sudo: required
addons:
  apt:
    packages:
    - google-cloud-sdk
language: java
jdk:
  - oraclejdk7
before_install:
  - sudo mkdir -p /usr/local/share/google
  - sudo ln -sv /usr/lib/google-cloud-sdk /usr/local/share/google/google-cloud-sdk
  - sudo gcloud --quiet components install app-engine-python
  - sudo gcloud --quiet components install app-engine-java
install: true
script: mvn -B verify
